In [64]:
import numpy as np

In [65]:
list_sus=[1,2,3,4,5]
sushil_arr=np.array(list_sus)
print(type(sushil_arr))

<class 'numpy.ndarray'>


In [66]:
sushil_arr.shape

(5,)

# Creating Two Dimensional Array

# In the below cell we have created a two-dimensional array, since we know that array can strore only similar type of values, so if any of the element of the array is different it will by default consider all other elements of the array of the same datatype.

In [67]:
list_sus2=[2,3,4,5,6]
list_sus3=[9,7,6,8,9]
sushil_arr_2=np.array([list_sus,list_sus2,list_sus3])
print(sushil_arr_2)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


# While reshaping the array make sure that the re-shaped array should also have the same no. of element as in the original array.

In [55]:
sushil_arr_2.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [9],
       [7],
       [6],
       [8],
       [9]])

# Fetching Array Elements

In [68]:
sushil_arr_2[0]

array([1, 2, 3, 4, 5])

In [69]:
sushil_arr_2[0][0]

1

In [70]:
sushil_arr_2[0:1,:]

array([[1, 2, 3, 4, 5]])

In [74]:
sushil_arr_2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [76]:
sushil_arr_2[1:,2:4]

array([[4, 5],
       [6, 8]])

# Using np.arrange

In [82]:
sus_arrange=np.arange(0,100,3)
sus_arrange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# np linspace

In [85]:
sus_lin=np.linspace(0,10,10)
sus_lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# Copy function in Array

# Array is basically a reference type. So once if we assign teh original array variable to another variable, then the changes in the secondary variable will also be reflected in the original array variable.
# So It's better to make a copy of the array and then perform operation on it.

In [87]:
arr_org=np.arange(0,13)
arr_org

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
arr_temp=arr_org
arr_temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
arr_temp[5:]=45
arr_org

array([ 0,  1,  2,  3,  4, 45, 45, 45, 45, 45, 45, 45, 45])

# See in the above cell the changes done to the temp array is also reflected in the original array, that is becaus array is a "reference type"

In [96]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [97]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [106]:
random_no_generator=np.random.rand(2)
random_no_generator

array([0.27997155, 0.4556898 ])

In [107]:
random_gen=np.random.randn(5,5)
random_gen

array([[ 1.09116469, -1.2032018 , -1.46908485,  1.35102667,  0.42726782],
       [-1.01851673, -0.18291513,  2.44700118, -1.53894278, -0.15183617],
       [ 0.928408  , -0.12344403,  2.09774958,  0.72946838, -0.04962838],
       [-0.70461349, -0.02537916,  0.28718129,  0.10149507,  1.33901306],
       [-0.66222651, -0.02497356,  0.38965627,  0.84705666, -0.08185579]])

# Now we will plot the random gen as the numbers are selected randombly but uniformly distribute. But that can be proved by plotting it on graph and observing its distributiuon.

In [110]:
import seaborn as sns
import pandas as pd

In [122]:
er=pd.DataFrame(random_gen,columns=['a','b','c','d','e'],index=['sus','isha','him','prakhar','pranab'])
er

a         b         c         d         e
sus      1.091165 -1.203202 -1.469085  1.351027  0.427268
isha    -1.018517 -0.182915  2.447001 -1.538943 -0.151836
him      0.928408 -0.123444  2.097750  0.729468 -0.049628
prakhar -0.704613 -0.025379  0.287181  0.101495  1.339013
pranab  -0.662227 -0.024974  0.389656  0.847057 -0.081856

In [123]:
sns.distplot(pd.DataFrame(random_gen))

C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)


<AxesSubplot:ylabel='Density'>

# As we can see the plot is a Bell curve, which states the Gaussian distribution among values which are uniformly distributed.

# Thank you
# Sushil